server {
    listen 80;
    server_name sonoradigitalcorp.com www.sonoradigitalcorp.com;

    root /var/www/sonora-digital-corp;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
